## Homework H08

L15

\
\
**Problem 1: 2 marks**
\
Define a function that accepts a vector of floats, scans each element, and reports the index of the first one that exceeds a specified threshold.  If no such element is found, return -1.
```
    first_above(vec, thresh)
```
To test your function, generate a random vector of 1000 floats, with values between 0 and 1.  Set the random seed to 12345.  Then run two tests, as follows:
```
    print(first_above(vec, 0.99))
    print(first_above(vec, 100))
```

In [1]:
import numpy as np

def first_above(vec, thresh):
    for i, value in enumerate(vec):
        if value > thresh:
            return i
    return -1

np.random.seed(12345)

vec = np.random.rand(1000)

print(first_above(vec, 0.99))
print(first_above(vec, 100))


26
-1


\
\
**Problem 2: 2 marks**
\
Define a function `neg_average` that accepts a vector and returns the average of all its negative values.  (Note that the resulting average will of course be a negative value).  Be careful to check that the vector actually contains any negative values.
\
\To test your function, generate two vectors of 1 million floats each, using `random.uniform`.  Set the random seed to 444.  For the first vector, generate random numbers in the range -5 to +8.  For the second, set the random seed to 555 and generate numbers in the range 1 to 8.  Print the resulting averages, to 2 decimal places.

In [4]:
import random

def neg_average(vec):
    negative_values = [x for x in vec if x < 0]

    if not negative_values:
        return 0

    return np.mean(negative_values)

# Set random seed for reproducibility
random.seed(444)
vec1 = np.random.uniform(-5, 8, size=1000000) #-5 +8

random.seed(555)
vec2 = np.random.uniform(1, 8, size=1000000) # 1 to 8 

print(f"Average of negative values in vec1: {neg_average(vec1):.2f}")
print(f"Average of negative values in vec2: {neg_average(vec2):.2f}")


Average of negative values in vec1: -2.50
Average of negative values in vec2: 0.00


\
\
**Problem 3: 2 marks**
\
Below is a tiny program.  It keeps adding 0.1 to `sum` until `sum` hits the value 1.0.
\
Type this program into a Jupyter Notebook or Spyder window and run it.  You will find that it never stops!

```
sum = 0.0
inc = 0.1

while True:               # 'forever' loop
    sum += inc
    if (sum == 1.0):
        break

print(f"sum = {sum}")
```
Work out what's going on.  Why does it keep running forever?  How would you fix the program so that it stops when the sum reaches 1.0?  Explain the steps you took to solve this question. 

In [ ]:
sum = 0.0
inc = 0.1

while True:               # 'forever' loop
    sum += inc
    if (sum == 1.0):
        break

print(f"sum = {sum}")

clearly, the sum never reacher 1.0, 

after running it it reaches 1.0 but never 1.0 exacly so the answer is simply make the == sign into a > sign

rightt.... steps 

i rans two print statments to see what sum was doing and then i made the executive desison to change == into > 

In [8]:
sum = 0.0
inc = 0.1

while True:               # 'this solution makes it stop when it crosses 1.0 
    sum += inc
    if (sum > 1.0):
        break

print(f"sum = {sum}")

sum = 1.0999999999999999


\
\
**Problem 4: 2 marks**
\
\
Define a function called `how_many`.  It takes two parameters: the first is a numpy vector (1-dimensional array); the second is an integer.  The function works out how many times the specified integer value occurs in the array.

Set the random number generator seed to 31416.  Generate a vector holding 20 random numbers in the range 1 to 10, inclusive.  Call `how_many` to find how many 10s are in the vector.  Print out the vector, and the number of 10s found

In [12]:
def how_many(vector, value):
    occurrences = np.count_nonzero(vector == value)
    return occurrences

np.random.seed(31416)

random_vector = np.random.randint(1, 11, size=20) #semi random vector

value_to_count = 10
count_of_value = how_many(random_vector, value_to_count)

print(f"Generated Vector: {random_vector}") 
print(f"Number of {value_to_count}s found: {count_of_value}") # what to find and how many found


Generated Vector: [ 7  3 10  8  8  6  2  8  7  4  2  5  1  2  5  6 10  6  8  9]
Number of 10s found: 2


\
\
**Problem 5: 2 marks**
  
Write a function called `filter`.  It takes a numpy vector of numbers.  The first negative number in that vector should be taken as the end of the vector.  (We might imagine that the numbers are measured signals, in microAmps, from a seismic experiment.  But the context does not actually matter).  `filter` should calculate the average value of numbers in the vector, but only those that lie between 1.000 and 3.000.  It should discard all others.

Run you function on the vector: [3.3, 1.2, 0.5, 0.88, 2.89, 2.4, 5.3, 7.26, 0.9, 1.3, 4.1, -1.23, 4.2] and print the resulting average, rounded to 3 decimal places

In [14]:
def filter(vector):
    end_index = np.argmax(vector < 0) 
    filtered_values = vector[:end_index] 

    filtered_values = filtered_values[(filtered_values >= 1.000) & (filtered_values <= 3.000)]

    if len(filtered_values) == 0:
        return 0 

    return round(np.mean(filtered_values), 3)  

given_vector = np.array([3.3, 1.2, 0.5, 0.88, 2.89, 2.4, 5.3, 7.26, 0.9, 1.3, 4.1, -1.23, 4.2])

print(f"Filtered Average: {filter(given_vector)}")


Filtered Average: 1.948


\
\
**Problem 6: BONUS: 4 marks***
\
Create a 2-D array (matrix or table) with 7 rows and 8 columns, full of zeros.  Ensure the data type of each element is numpy.int64.  Use slicing to generate the pattern below.  (1s in top row, 2s in bottom row, 3s in left column, 4s in right column, in that order).  Print out the matrix.  Do not use any loops.

`3 1 1 1 1 1 1 4
 3 0 0 0 0 0 0 4
 3 0 0 0 0 0 0 4
 3 0 0 0 0 0 0 4
 3 0 0 0 0 0 0 4
 3 0 0 0 0 0 0 4
 3 2 2 2 2 2 2 4`
 
Now use slicing to copy 3 elements from the start of row 0 into the start of column 2.  Print out this matrix.    (Please print a blank line after the previous answer).  Do not use any loops.
 
`3 1 3 1 1 1 1 4
 3 0 1 0 0 0 0 4
 3 0 1 0 0 0 0 4
 3 0 0 0 0 0 0 4
 3 0 0 0 0 0 0 4
 3 0 0 0 0 0 0 4
 3 2 2 2 2 2 2 4`
 
Now use slicing to set row 4, columns 2 thru 5 inclusive, to the value 7.  Print out this matrix.  (Please print a blank line after the previous answer).  Do not use any loops.
 
`3 1 3 1 1 1 1 4
 3 0 1 0 0 0 0 4
 3 0 1 0 0 0 0 4
 3 0 0 0 0 0 0 4
 3 0 7 7 7 7 0 4
 3 0 0 0 0 0 0 4
 3 2 2 2 2 2 2 4`
 
Now use slicing to print rows 1 thru 4 inclusive, for columns 5 thru 7, inclusive.  (Please print a blank line after the previous answer).  Do not use any loops.
 
`0 0 4
 0 0 4
 0 0 4
 7 0 4`

In [40]:
import numpy as np

# Create a 7x8 matrix of zeros with data type np.int64
matrix = np.zeros((7, 8), dtype=np.int64)

# Assign 1s to the top row, 2s to the bottom row, 3s to the left column, and 4s to the right column
matrix[0, :] = 1
matrix[-1, :] = 2
matrix[:, 0] = 3
matrix[:, -1] = 4

# Print the matrix after assigning 1s, 2s, 3s, and 4s
print(matrix) # first matrix 
print()  # Blank line after the previous answer

# Copy 3 elements from the start of row 0 into the start of column 2 using slicing
matrix[0:3, 2] = matrix[0, 0:3]

# Print the matrix after copying elements
print(matrix)
print()  # Blank line after the previous answer

# Set row 4, columns 2 through 5 inclusive, to the value 7 using slicing
matrix[4, 2:6] = 7

# Print the matrix after setting values to 7
print(matrix)
print()  # Blank line after the previous answer

# Print rows 1 through 4 inclusive for columns 5 through 7 inclusive using slicing
print(matrix[1:5, 5:8])


[[3 1 1 1 1 1 1 4]
 [3 0 0 0 0 0 0 4]
 [3 0 0 0 0 0 0 4]
 [3 0 0 0 0 0 0 4]
 [3 0 0 0 0 0 0 4]
 [3 0 0 0 0 0 0 4]
 [3 2 2 2 2 2 2 4]]

[[3 1 3 1 1 1 1 4]
 [3 0 1 0 0 0 0 4]
 [3 0 1 0 0 0 0 4]
 [3 0 0 0 0 0 0 4]
 [3 0 0 0 0 0 0 4]
 [3 0 0 0 0 0 0 4]
 [3 2 2 2 2 2 2 4]]

[[3 1 3 1 1 1 1 4]
 [3 0 1 0 0 0 0 4]
 [3 0 1 0 0 0 0 4]
 [3 0 0 0 0 0 0 4]
 [3 0 7 7 7 7 0 4]
 [3 0 0 0 0 0 0 4]
 [3 2 2 2 2 2 2 4]]

[[0 0 4]
 [0 0 4]
 [0 0 4]
 [7 0 4]]
